# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-29 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=64, verbose_name='客户端名称')),
                ('score', models.IntegerField(verbose_name='分值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户端分值表',
                'verbose_name_plural': '客户端分值表',
            },
        ),
        migrations.CreateModel(
            name='RankingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=64, verbose_name='客户端名称')),
                ('score', models.IntegerField(verbose_name='分值')),
            ],
            options={
                'verbose_name': '客户端排名表',
                'verbose_name_plural': '客户端排名表',
                'ordering': ['score'],
            },
        ),
    ]
